### ISSUE TITLE
Auto show complete window

### ISSUE THREAD

**Issue by Sanysvo** [bobbylight/AutoComplete#72]
Hi, how i can do it: i want press trigger key, i want print code and get autocomplete window.

**Comment by wangqs-mobilestone** [comment]
```
provider.setAutoActivationRules(true, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");

```

**Comment by bobbylight** [comment]
You should be able to get away with just:

```java
provider.setAutoActivationRules(true, null);
```

Since the boolean first param should auto-add `[A-Za-z]` (really, after anything matching `Character.isCharacter(char)`).

The second param is for additional, non-letter characters, such as `.` if you built in the smarts for method completions:

```java
provider.setAutoActivationRules(true, ".");
```

Or were adding auto-complete for a language where non-letter characters were valid in an identifier, such as `$`:

```java
provider.setAutoActivationRules(true, "$");
```
