### ISSUE TITLE
CompletionProvider works but doesn't update

### ISSUE THREAD

**Issue by Guarmanda** [bobbylight/AutoComplete#78]
I created a completion provider, added all C functions for it, and they correctly show when I type something then ctrl+ escape.
But when I create new functions, or when I use an old file with some function already coded, the completion Provider doesn't update at all. I have the same problem for syntax highlighting: new functions aren't coloured.

**Comment by bobbylight** [comment]
The built-in `CompletionProvider`s such as `DefaultCompletionProvider` don't parse documents to provide semantic highlighting.  They instead allow for code completion of a static set of completion choices, such as the C stdlib, Perl builtin functions or the JDK.

In order to have dynamic code completions, you'd need to write a custom [Parser](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/parser/Parser.java) that knows how to parse the programming language you're interested in, and use it to feed completion values to your custom `CompletionProvider` implementation.  For the best examples of how to do this, check out the `RSTALanguageSupport` project, which has implemented a custom AST for code completion of Java local variables and methods, uses a custom parser for completing variable names in languages such as Perl and PHP, and more.
